name: Deploy applicatie

on: push

jobs:
  plan:
    name: Terraform plan
    # runner draait op de laatste versie van ubuntu met node.js 26
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 26.x
        uses: actions/setup-node@v1
        with:
          node-version: '26'
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      # Logt in bij AWS met de credentials die in de secrets staan
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
      # Initialiseert terraform en plant het project
      - name: Initialise project and view terraform plan
        run: |
            cd terraform 
            terraform fmt
            terraform init
            terraform plan

  deploy-rds:
    # runner draait op de laatste versie van ubuntu met node.js 26
    name: deploy-rds
    # needs kan worden omgedraait, zodat bij het bouwen eerst de rds en daarna de app aan de berut is, en bij verijderen andersom.
    # bij aanmaken
    needs: plan
    # bij verwijderen
    # needs: deploy-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 26.x
        uses: actions/setup-node@v1
        with:
          node-version: '26'
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
     # Initialiseert terraform en deployt de infra
      - name: deploy infra with terraform
        run: |
          cd terraform
          terraform fmt
          terraform init
          # afhankelijk van welke wordt gekozen wordt de infra gemaakt of verwijderd.
          terraform apply -auto-approve
          # terraform destroy -auto-approve


# is hetzelfde als de bovenste, deze maakt de app aan
  deploy-app:
    name: deploy-app
    # bij aanmaken
    needs: deploy-rds
    #bij verwijderen
    # needs: plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 26.x
        uses: actions/setup-node@v1
        with:
          node-version: '26'
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: deploy infra with terraform
        run: |
          cd terraform-app
          terraform fmt
          terraform init
          terraform apply -auto-approve
          # terraform destroy -auto-approve